# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - wecham

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_1880c93173694d229845c99429714b17 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_ae7be56810324448953072deb4b82d1a }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_1880c93173694d229845c99429714b17 }}/rw:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'wecham'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_d4ace1339548454ca2b24ddda6066099 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_1880c93173694d229845c99429714b17 }}/rw:${{ github.sha }}'